-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 22, 2023 at 10:12 AM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `art-gallery`
--

-- --------------------------------------------------------

--
-- Table structure for table `account`
--

CREATE TABLE `account` (
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `status` varchar(20) NOT NULL,
  `highscore` int(255) NOT NULL,
  `score` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `account`
--

INSERT INTO `account` (`username`, `password`, `status`, `highscore`, `score`) VALUES
('agi', 'agi', 'user', 70, 100),
('kansha', 'kansha', 'user', 14, 0),
('isna', 'isna', 'admin', 20, 80);

-- --------------------------------------------------------

--
-- Table structure for table `art`
--

CREATE TABLE `art` (
  `no` int(255) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `artist` varchar(50) NOT NULL,
  `tahun` int(11) NOT NULL,
  `gambar` varchar(255) NOT NULL,
  `jenis` varchar(50) NOT NULL,
  `deskripsi` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `art`
--

INSERT INTO `art` (`no`, `nama`, `artist`, `tahun`, `gambar`, `jenis`, `deskripsi`) VALUES
(1, 'Mona Lisa', 'Leonardo da Vinci', 1803, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\Mona Lisa.jpg', 'Lukisan', 'Mona Lisa, dipercaya menjadi karya seni paling ikonik sepanjang sejarah, adalah lukisan potret yang diciptakan oleh seniman Italia terkenal Leonardo da Vinci pada abad ke-16. Mona Lisa mungkin menjadi lukisan yang paling banyak dikenal di dunia, sebagian besar karena senyuman misterius yang terpatri di wajah wanita dalam lukisan itu. Kehidupan dan seni da Vinci tercermin dalam setiap detailnya, mulai dari teknik penggambaran yang brilian hingga penggunaan cahaya yang menakjubkan.\n\nLukisan ini menggambarkan seorang wanita dengan postur anggun dan latar belakang lanskap yang indah. Keutamaan diberikan pada wajah Mona Lisa yang menarik perhatian pengamat dengan senyuman yang kabur namun memikat. Senyum Mona Lisa sering kali dianggap sebagai kunci misteri dan daya tariknya. Lukisan ini juga dikenal dengan penggunaan teknik sfumato, yaitu teknik melukis dengan gradasi warna yang lembut, memberikan efek seperti kabut yang menyelimuti wajah wanita itu.\n\nKeindahan Mona Lisa tidak hanya terletak pada wajahnya yang memukau, tetapi juga pada perpaduan harmonis antara elemen-elemen artistiknya. Lukisan ini telah memikat hati dan imajinasi pengunjung Louvre di Paris, tempat lukisan ini dipamerkan. Keberadaannya telah memberikan kontribusi besar terhadap dunia seni dan menjadi simbol universal dari keindahan dan misteri dalam seni rupa.'),
(3, 'The Persistence of Memory', 'Salvador Dalí', 1931, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Persistence of Memory.jpg', 'Lukisan', '\"The Persistence of Memory\" adalah salah satu karya ikonik dari pelukis Spanyol Salvador Dalí. Lukisan ini diciptakan pada tahun 1931 dan menjadi salah satu karya paling terkenal dalam aliran seni surealis. Dalam karyanya ini, Dalí menggambarkan dunia yang surreal dan fantastis dengan cara yang sangat unik. Lukisan ini terkenal karena gambaran jam-jam meleleh yang lentur dan wajah yang lemas, menciptakan atmosfer yang tak nyata dan mendalam.\n\nSalvador Dalí menggunakan \"The Persistence of Memory\" untuk menggambarkan konsep relativitas waktu. Jam-jam yang meleleh menciptakan ilusi waktu yang lentur dan elastis, mengekspresikan ide bahwa waktu tidak selalu diukur dengan cara yang kaku dan konvensional. Lukisan ini sering diinterpretasikan sebagai refleksi terhadap ketidakstabilan waktu dan ketidakpastian dalam kehidupan, serta sebagai ungkapan dari perasaan Dalí terhadap relatifitas realitas.\n\nKarya ini memberikan pandangan yang menggugah pikiran tentang hubungan antara waktu dan kenyataan, sementara gaya surealis Dalí yang unik dan detail ilustrasinya membuatnya menjadi salah satu karya seni paling dikenal dalam sejarah. \"The Persistence of Memory\" tidak hanya menunjukkan kejelian Dalí dalam menangkap konsep-konsep kompleks, tetapi juga menyajikan pandangan surealis yang memprovokasi dan mendalam terhadap sifat waktu dan realitas.'),
(2, 'The Starry Night', 'Vincent Van Gogh', 1889, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Starry Night.jpeg', 'Lukisan', '\"The Starry Night\" adalah sebuah karya seni besar yang dihasilkan oleh pelukis Belanda Vincent van Gogh pada tahun 1889. Lukisan ini menciptakan pemandangan malam yang luar biasa dengan langit yang penuh bintang di atas kota kecil Saint-Rémy-de-Provence, tempat Van Gogh tinggal sementara di rumah sakit jiwa Saint-Paul-de-Mausole. Dibuat selama periode intensitas kreatifnya, lukisan ini mencerminkan pengaruh seni ekspresionis yang kuat dan ketertarikan pribadi sang seniman pada alam dan kehidupan spiritual.\n\nDengan goresan kuas yang dinamis dan pemilihan warna yang dramatis, Van Gogh menghadirkan suasana magis yang merayakan keajaiban alam. Langit biru mendalam dipenuhi dengan gerakan garis yang melambangkan energi dan kegilaan. Bintang-bintang yang melingkupi langit menciptakan ritme visual yang kuat, sementara desainnya yang eksperimental menunjukkan dorongan artistik Van Gogh untuk memperluas batas-batas seni tradisional pada masanya.\n\n\"The Starry Night\" telah menjadi salah satu karya paling ikonik dalam sejarah seni rupa Barat. Lukisan ini tidak hanya menggambarkan kekaguman dan ketakjuban terhadap keindahan alam, tetapi juga mencerminkan keadaan emosional dan psikologis pelukis. Kekuatan dan daya tarik karya ini telah membuatnya menjadi simbol penghargaan dan pengakuan terhadap ketidakdewasaan seorang seniman yang sangat dihargai dalam dunia seni.'),
(4, 'The Creation of Adam', 'Michelangelo', 1512, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Creation of Adam.jpeg', 'Lukisan', '\"The Creation of Adam\" adalah salah satu bagian dari karya monumental Michelangelo yang dikenal sebagai Sistine Chapel ceiling. Lukisan ini dibuat oleh seniman Italia Renaissance, Michelangelo Buonarroti, antara tahun 1508 dan 1512, di Kapel Sistina, Kota Vatikan. Lukisan ini menggambarkan narasi penciptaan Adam, seperti yang terdapat dalam Kitab Kejadian dalam Alkitab. \"The Creation of Adam\" menjadi salah satu ikon seni rupa Barat dan menggambarkan momen ketika Tuhan memberikan kehidupan kepada Adam dengan sentuhan-Nya.\n\nDengan latar belakang yang memukau dari langit-langit Kapel Sistina, \"The Creation of Adam\" menampilkan sosok Tuhan yang memanjang, mengulurkan tangan-Nya menuju Adam. Gaya klasik Michelangelo terlihat dalam proporsi tubuh yang sempurna dan detail anatomi yang presisi. Ekspresi artistiknya menangkap ketegangan dramatis dari momen tersebut, menciptakan karya seni yang mencerminkan kekuasaan ilahi dan hubungan intim antara pencipta dan manusia pertama.\n\nKeindahan dan kompleksitas karya ini tidak hanya terletak pada teknik melukisnya, tetapi juga dalam kemampuan Michelangelo untuk menyampaikan tema teologis dengan sangat kuat. \"The Creation of Adam\" tidak hanya menjadi pencapaian artistik yang luar biasa, tetapi juga merupakan ekspresi mendalam tentang keyakinan dan pandangan dunia pada masa Renaissance. Karya ini terus menjadi objek kagum dan pemujaan dalam dunia seni rupa sepanjang sejarah.'),
(5, 'Guernica', 'Pablo Picasso', 1937, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\Guernica.jpeg', 'Lukisan', '\"Guernica\" adalah karya monumental yang diciptakan oleh seniman Spanyol Pablo Picasso pada tahun 1937. Lukisan ini dihasilkan sebagai tanggapan Picasso terhadap peristiwa tragis dalam Perang Saudara Spanyol ketika pasukan Jerman dan Italia yang didukung oleh diktator Spanyol, Francisco Franco, melakukan pengeboman terhadap kota Guernica pada 26 April 1937. Peristiwa ini menyebabkan korban sipil yang besar dan merusakkan kota secara menyeluruh. \"Guernica\" mencerminkan ketakutan, kebingungan, dan penderitaan yang dihasilkan oleh perang dan kekejaman manusia terhadap sesamanya.\n\nTahun 1937 adalah masa ketika Perang Saudara Spanyol sedang berkecamuk, dan seni menjadi saluran ekspresi bagi Picasso untuk menyuarakan keprihatinannya terhadap tragedi tersebut. \"Guernica\" merupakan lukisan besar berukuran 349 cm × 776 cm yang menggambarkan pemandangan kacau kebingungan, dengan bentuk-bentuk yang terdistorsi dan penuh dengan rasa penderitaan. Warna monokromatik, dominasi warna hitam, putih, dan abu-abu, memberikan kesan dramatis dan kehancuran yang mendalam. Picasso berhasil menggambarkan ketakutan dan kekejaman perang dengan simbol-simbol seperti kuda yang terluka, manusia dan binatang yang tergeletak, serta lambang-lambang lain yang mencerminkan tragisitas peristiwa tersebut.\n\n\"Guernica\" tidak hanya menjadi karya seni yang sangat berpengaruh dalam sejarah seni rupa, tetapi juga menjadi simbol anti-perang yang kuat. Sejak pembuatannya, lukisan ini telah menjadi ikon global yang mengingatkan dunia akan konsekuensi destruktif dari konflik bersenjata. Dengan kekuatannya yang mengguncang dan pesan anti-perang yang mendalam, \"Guernica\" tetap menjadi karya seni yang meresap dan menggerakkan hati penonton hingga saat ini.'),
(6, 'The Thinker', 'Auguste Rodin', 1881, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Thinker.jpeg', 'Patung', '\"The Thinker\" adalah salah satu karya seni paling ikonik yang diciptakan oleh seniman Prancis Auguste Rodin. Patung ini pertama kali dibuat pada tahun 1881 sebagai bagian dari komisi untuk dekorasi fasad Museum Dekoratif Seni Terapan di Paris. Karya ini kemudian menjadi salah satu karya paling terkenal dan diakui di dunia seni rupa. \"The Thinker\" menggambarkan seorang pria yang duduk dalam pose merenung dengan kepala yang ditopang oleh tangannya yang bersandar pada dahi. Patung ini menciptakan kesan introspeksi dan serius, mencerminkan proses pemikiran dan kontemplasi yang mendalam.\n\nDalam menciptakan \"The Thinker,\" Rodin terinspirasi oleh puisi Dante Alighieri, \"Divine Comedy,\" khususnya menggambarkan tokoh Dante Alighieri sendiri yang sedang berada di Pintu Neraka. Meskipun, awalnya, patung ini didesain sebagai bagian dari sebuah gerbang museum, keberhasilan karya ini membawa \"The Thinker\" menjadi karya yang berdiri sendiri dan dihargai oleh banyak orang sebagai simbol universal dari pemikiran manusia yang mendalam.\n\nKekuatan \"The Thinker\" tidak hanya terletak pada rinciannya yang luar biasa dan ekspresi yang mendalam, tetapi juga pada kemampuannya untuk meresapi perenungan dan makna filosofis. Karya ini telah menjadi ikon budaya yang mencerminkan kebijaksanaan dan refleksi, menjadikannya sebagai salah satu pencapaian luar biasa dalam sejarah seni rupa yang terus memukau dan menginspirasi penonton di seluruh dunia.'),
(7, 'The Kiss', 'Gustav Klimt', 1908, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Kiss.jpeg', 'Lukisan', '\"The Kiss\" adalah salah satu karya paling ikonik dari pelukis Austria, Gustav Klimt, yang diciptakan pada tahun 1907-1908. Karya ini memperlihatkan gaya Art Nouveau yang khas dan kecenderungan simbolisme yang sering ditemui dalam karya-karya Klimt. Dalam lukisan ini, seorang pria dan seorang wanita yang terbungkus dalam emas dan hiasan berpola, menggambarkan keintiman dan cinta romantis. Klimt mengekspresikan tema erotis dan sensualitas dengan cara yang menggambarkan keindahan dan kemewahan, serta memberikan sentuhan magis pada momen keintiman yang digambarkannya.\n\nDengan penggunaan emas dan dekorasi yang melimpah, \"The Kiss\" mencerminkan pengaruh seni Bizantium dan gaya dekoratif dari seni tradisional Jepang. Hal ini menciptakan atmosfer yang sangat elegan dan mewah, menambah dimensi artistik pada karya tersebut. Klimt tidak hanya mengeksplorasi relasi manusia dalam konteks cinta dan keintiman, tetapi juga menyajikan karya seni yang menjadi ikon budaya dengan pesona estetis yang kuat.\n\nSejak pembuatannya, \"The Kiss\" telah menjadi salah satu lukisan paling terkenal dan dihargai dalam sejarah seni. Karya ini tidak hanya mewakili kecemerlangan artistik Klimt, tetapi juga melambangkan perubahan dalam gaya seni rupa pada awal abad ke-20. Lukisan ini terus mempesona penonton dengan keindahan dan romantisme yang tak lekang oleh waktu, menunjukkan daya tarik dan keberlanjutan seni yang tak terbatas.'),
(8, 'The Birth of Venus', 'Sandro Botticelli', 1486, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Birth of Venus.jpeg', 'Lukisan', '\"The Birth of Venus\" adalah salah satu karya masterpiece yang dihasilkan oleh pelukis Renaissance Italia, Sandro Botticelli. Lukisan ini diperkirakan dibuat pada sekitar tahun 1484–1486 dan menjadi salah satu karya paling ikonik dari periode tersebut. Botticelli menciptakan karya ini untuk Lorenzo di Pierfrancesco de\' Medici, seorang tokoh terkemuka pada masa itu, dan sejak itu menjadi salah satu lukisan paling terkenal dalam koleksi seni Renaissance.\n\nLukisan ini menggambarkan dewi Venus yang lahir dari lautan di tengah-tengah kerang raksasa, diinspirasi oleh mitologi Romawi dan Yunani kuno. Dewi Venus, atau yang dikenal sebagai dewi cinta dan kecantikan, dihadirkan dengan keanggunan dan kecantikan yang luar biasa. Dalam gaya Renaissance yang khas, Botticelli menampilkan detail anatomi yang halus, goresan kuas yang lembut, dan komposisi yang harmonis. Kombinasi warna-warna yang indah dan bentuk-bentuk yang elegan menciptakan suasana keindahan yang timeless.\n\n\"The Birth of Venus\" juga melibatkan elemen-elemen mitologis, seperti Zephyr dan Chloris di sisi kanan, serta Horae di sebelah kiri, menambahkan dimensi keagungan dan keajaiban pada lukisan ini. Dengan penggambaran yang begitu indah dan simbolisme mitologis yang mendalam, karya ini telah menjadi objek studi yang penting dalam sejarah seni dan tetap memikat para penikmat seni rupa hingga saat ini.'),
(9, 'Liberty Leading the People', 'Eugène Delacroix', 1830, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\Liberty Leading the People.jpeg', 'Lukisan', '\"Liberty Leading the People\" adalah salah satu lukisan terkenal yang diciptakan oleh pelukis Prancis Eugène Delacroix pada tahun 1830. Lukisan ini dihasilkan sebagai respon terhadap Revolusi Juli di Prancis yang terjadi pada waktu yang sama. Delacroix menggambarkan alegori kebebasan yang memimpin rakyat Prancis ke depan dengan semangat revolusioner yang membara. Ia melukiskan figur kebebasan sebagai wanita yang gagah berani, mengenakan topi phrygian merah yang menjadi simbol revolusi, dan memegang bendera trikolor Prancis yang terkenal.\n\n\"Liberation Leading the People\" menonjolkan gaya romantis dan dramatis yang khas dari Delacroix. Pemilihan warna yang kuat, goresan kuas yang dinamis, dan komposisi yang berani menciptakan suasana yang penuh semangat dan berapi-api. Lukisan ini memadukan elemen realisme dengan elemen romantisme, mengekspresikan semangat perubahan dan kebebasan yang terus berkobar dalam masyarakat Prancis pada saat itu. Karya ini juga mencerminkan pengaruh besar seniman terhadap pergerakan seni modern, menjadikannya salah satu lukisan terpenting dalam sejarah seni Prancis.\n\nSejak diciptakan, \"Liberty Leading the People\" tetap menjadi karya ikonik yang menginspirasi dan menjadi simbol semangat revolusioner. Lukisan ini dikenal oleh banyak orang karena kemampuannya yang luar biasa untuk merangkum momen sejarah penting dan merayakan semangat kebebasan yang tetap relevan dalam konteks zaman.'),
(10, 'The Night Watch', 'Rembrandt van Rijn', 1642, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Night Watch.jpeg', 'Lukisan', '\"The Night Watch\" atau dalam bahasa Belanda dikenal sebagai \"De Nachtwacht\" merupakan salah satu mahakarya lukisan karya pelukis Belanda Rembrandt van Rijn. Lukisan ini diselesaikan pada tahun 1642 dan menjadi salah satu karya terkenal dalam sejarah seni Barat. \"The Night Watch\" sejatinya adalah potret kelompok milisi sipil di Amsterdam yang dipimpin oleh kapten Frans Banning Cocq dan letnan Willem van Ruytenburch. Meskipun namanya bisa mengecoh, lukisan ini tidak menggambarkan suasana malam, melainkan merupakan hasil dari perubahan warna dan kualitas lukisan seiring waktu.\n\nRembrandt menghadirkan keunikannya dalam \"The Night Watch\" dengan keahlian teknis dan kecerdasan artistiknya. Lukisan ini menampilkan kelompok milisi dalam aksi, dengan dramatisasi cahaya dan bayangan yang khas Rembrandt. Fokusnya bukan hanya pada para pemimpin milisi, tetapi juga pada anggota kelompok yang beragam, menciptakan kesan dinamis dan penuh kehidupan. Rembrandt menggunakan teknik chiaroscuro, yaitu kontras antara area terang dan gelap, untuk menyoroti detail wajah dan pakaian para figur, menciptakan karya yang memukau secara visual dan bercerita secara naratif.\n\nMeskipun \"The Night Watch\" awalnya menerima kritik karena gaya penceritaannya yang lebih dinamis dan tidak konvensional, karya ini seiring waktu diakui sebagai salah satu pencapaian puncak seni lukis Barat. Kombinasi keahlian teknis Rembrandt, dramatisasi cahaya, dan narasi yang penuh semangat menjadikan lukisan ini salah satu ikon seni Rijksmuseum di Amsterdam dan sebuah tolok ukur dalam sejarah seni Barat.'),
(11, 'The Great Wave off Kanagawa', 'Katsushika Hokusai', 1833, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Great Wave off Kanagawa.jpeg', 'Lukisan', '\"The Great Wave off Kanagawa\" (浮世絵 神奈川沖浪裏, Fugaku Ukiyoe, Kanagawa-oki Nami Ura) adalah karya seni ukiyo-e klasik yang diciptakan oleh seniman Jepang terkenal, Katsushika Hokusai. Lukisan ini pertama kali diterbitkan sekitar tahun 1831 hingga 1833 sebagai bagian dari serangkaian karya bertajuk \"Tiga Puluh Enam Pemandangan Gunung Fuji\" (Fugaku Sanjūrokkei). Karya ini adalah salah satu puncak pencapaian seni ukiyo-e dan menjadi salah satu ikon seni Jepang yang paling terkenal di seluruh dunia.\n\nLukisan ini menampilkan gelombang besar yang bergulung tinggi di lepas pantai Kanagawa, dengan Gunung Fuji yang megah terlihat di latar belakang. Keberanian dan kekuatan gelombang yang digambarkan oleh Hokusai menciptakan suasana dramatis dan dinamis dalam lukisan ini. Teknik cetak ukiyo-e yang digunakan Hokusai memberikan detail yang halus pada gelombang, dan penggunaan warna biru yang khas menjadi ciri khas utama karya ini. \"The Great Wave off Kanagawa\" mencerminkan kekaguman Hokusai terhadap keindahan alam, sambil menggambarkan keteguhan manusia di hadapan kekuatan alam yang dahsyat.\n\nLukisan ini bukan hanya sebuah karya seni yang indah, tetapi juga telah menjadi simbol budaya Jepang dan lambang ketahanan dalam menghadapi bencana alam. Kombinasi desain yang mencolok, komposisi yang efektif, dan ekspresi seni yang kuat membuat \"The Great Wave off Kanagawa\" tetap relevan dan dihargai hingga saat ini, menunjukkan warisan seni besar dari Jepang dalam skala global.'),
(12, 'The Scream', 'Edvard Munch', 1893, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Scream.jpeg', 'Lukisan', '\"The Scream\" adalah salah satu karya ikonik yang diciptakan oleh seniman Norwegia Edvard Munch pada tahun 1893. Lukisan ini merupakan bagian dari serangkaian karya yang dikenal sebagai \"The Frieze of Life\" yang menggambarkan tema-tema emosional dan eksistensial. \"The Scream\" menjadi simbol universal ketidakpastian dan kecemasan, menangkap ketegangan psikologis dan kehampaan manusia.\n\nDengan latar belakang kota Oslo yang dilukiskan dengan warna-warna yang tidak alami dan langit yang terbakar dengan warna merah-oranye, lukisan ini menciptakan atmosfer yang menakutkan dan aneh. Tokoh utama dalam lukisan ini adalah seorang manusia yang melengkungkan tubuhnya dan menjerit tanpa suara, wajahnya yang melengkung dan menunjukkan ekspresi ketakutan yang ekstrem. Bentuk dan garis-garis yang distorsi menciptakan suasana yang suram dan tidak stabil, mencerminkan perasaan teror dan kebingungan yang mendalam.\n\nDalam sejarah seni, \"The Scream\" dianggap sebagai salah satu karya yang paling berpengaruh dan menginspirasi. Kehampaan dan ketidakpastian yang terpancar dari lukisan ini mampu mengekspresikan perasaan universal manusia, membuatnya menjadi ikon seni rupa ekspresionisme. \"The Scream\" bukan hanya sekadar lukisan, tetapi juga suatu karya seni rupa yang menyentuh dimensi psikologis kolektif, menimbulkan refleksi mendalam tentang kehidupan dan kondisi manusia.'),
(13, 'The Hay Wain', 'John Constable', 1821, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Hay Wain.jpeg', 'Lukisan', '\"The Hay Wain\" adalah sebuah lukisan terkenal karya pelukis Inggris John Constable, diselesaikan pada tahun 1821. Lukisan ini merupakan salah satu karya paling ikonik dalam seni rupa Romantisisme, menampilkan pemandangan pedesaan yang indah dan tenang di Sungai Stour di Suffolk, Inggris. Constable adalah seorang pelukis lanskap yang terkenal karena menciptakan karya-karya yang merefleksikan cinta dan kedalaman perasaannya terhadap alam dan lingkungannya.\n\nDalam \"The Hay Wain,\" Constable menggambarkan suasana damai di pedesaan yang tenang, dengan sebuah kereta luncur yang sedang melintas di sungai. Lukisan ini menampilkan detail alam yang teliti dan penuh dengan warna-warna yang alami, menciptakan suasana damai dan keindahan yang khas dari karya-karya Constable. Sang seniman dengan cermat menangkap cahaya dan nuansa warna, menciptakan efek realisme yang mengesankan.\n\nKarya ini mencerminkan pemikiran dan pandangan Constable terhadap keindahan alam, memperlihatkan keyakinannya bahwa seni dapat menjadi medium untuk menyampaikan keindahan sederhana di sekitar kita. \"The Hay Wain\" tidak hanya diakui sebagai suatu pencapaian artistik, tetapi juga sebagai karya yang merepresentasikan perasaan pribadi dan visi seniman terhadap keindahan pedesaan Inggris pada abad ke-19.'),
(14, 'The Arnolfini', 'Jan van Eyck', 1434, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Arnolfini.jpeg', 'Lukisan', 'Lukisan \"The Arnolfini Portrait\" atau \"Pernikahan Arnolfini\" merupakan karya master dari seniman Belanda abad ke-15, Jan van Eyck. Lukisan ini dibuat pada tahun 1434 dan menjadi salah satu karya paling terkenal dalam sejarah seni rupa Barat. Jan van Eyck dikenal sebagai salah satu pelopor seni lukis Flemish dan memainkan peran penting dalam perkembangan seni Renaissance di Eropa Utara.\n\nLukisan ini menggambarkan pasangan pernikahan, Giovanni Arnolfini dan istrinya, yang merupakan tokoh-tokoh terhormat dari kalangan pedagang di Bruges, Belgia. Dalam lukisan ini, van Eyck memperlihatkan keahliannya dalam penggunaan detail dan teknik cahaya yang realistis. Pada latar belakang, terdapat cermin yang memantulkan gambar sepasang pengantin dan dua sosok misterius lainnya, mengundang interpretasi dan diskusi seputar makna simbolisnya.\n\nDeskripsi lukisan mencakup perhatian yang cermat terhadap detail di setiap elemen, termasuk tekstur kaya pada karpet dan pakaian, serta penggunaan warna yang cerdas. Lukisan ini menjadi sumber inspirasi bagi seniman-seniman masa berikutnya dan masih memukau penonton hingga hari ini. \"The Arnolfini Portrait\" bukan hanya sebuah dokumentasi pernikahan, tetapi juga sebuah karya seni yang menyimpan kekayaan makna dan keindahan estetika, menandai kecemerlangan seni lukis pada periode Renaissance Utara.'),
(15, 'The Swing', 'Jean-Honoré Fragonard', 1767, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Swing.jpeg', 'Lukisan', '\"The Swing\" adalah sebuah lukisan ikonik yang diciptakan oleh pelukis Rococo ternama asal Prancis, Jean-Honoré Fragonard, pada tahun 1767. Lukisan ini menangkap keanggunan dan keceriaan gaya Rococo yang berkembang pada abad ke-18 di Eropa. Jean-Honoré Fragonard dikenal sebagai salah satu maestro Rococo, dan karyanya, termasuk \"The Swing,\" memancarkan sentuhan artistik yang berani dan estetika yang khas dari periode tersebut.\n\nLukisan ini menampilkan seorang wanita muda yang sedang digoyangkan oleh seorang pemuda di atas ayunan yang tergantung dari pohon. Wanita tersebut mengenakan gaun yang anggun dan cerah, sementara sepatu kaca yang dilepaskan di udara menambah sentuhan romantis pada adegan. Sementara wanita terbang di udara, seorang pria yang tersembunyi di semak-semak sedang menikmati pemandangan dari bawah. \"The Swing\" menciptakan suasana riang dan bebas, mencerminkan nilai-nilai kebebasan dan kesenangan yang dihargai pada masa Rococo.\n\nDengan warna-warna cerah, sentuhan lukisan yang ringan, dan detail yang halus, \"The Swing\" Fragonard menjadi karya yang menonjol dalam periode Rococo dan mewakili semangat kebebasan dan keceriaan yang menjadi ciri khas seni rupa pada masa itu. Lukisan ini terus menjadi salah satu lambang keanggunan dan keindahan era Rococo dalam sejarah seni rupa Barat.'),
(16, 'The Raft of the Medusa', 'Théodore Géricault', 1819, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Raft of the Medusa.jpeg', 'Lukisan', '\"The Raft of the Medusa\" adalah sebuah lukisan monumental yang diciptakan oleh seniman Prancis, Théodore Géricault, pada tahun 1818-1819. Karya ini menggambarkan sebuah peristiwa kontroversial di mana kapal fregat Prancis, Medusa, mengalami kecelakaan di lepas pantai Senegal pada tahun 1816. Lukisan ini terinspirasi oleh tragedi nyata di mana para penumpang kapal terdampar di rakit improvisasi dan harus bertahan hidup dalam kondisi yang sangat sulit.\n\nDengan gaya Romantis yang khas, Géricault menghadirkan kekacauan dan keputusasaan melalui komposisi dramatisnya. Lukisan ini mengeksplorasi tema kemanusiaan, penderitaan, dan kehancuran, menciptakan karya seni yang membangkitkan empati dan refleksi. Géricault memperlihatkan ketegangan dan konflik di antara para korban, dengan beberapa orang berjuang untuk hidup dan yang lainnya menghadapi kematian yang tak terelakkan. Detail-detail realistis dalam karya ini menyampaikan kekejaman dan ketidakpastian dalam situasi yang tragis tersebut.\n\n\"The Raft of the Medusa\" dianggap sebagai salah satu masterpiece seni Romantis dan merupakan wujud keberanian seniman dalam menghadapi realitas kehidupan manusia. Lukisan ini juga memainkan peran penting dalam sejarah seni, memperkenalkan pendekatan baru terhadap representasi dramatis dan melibatkan pengamat dalam narasi yang memilukan. Karya ini tidak hanya menjadi sukses artistik, tetapi juga menciptakan impak sosial dengan menyuarakan keprihatinan dan kritik terhadap kebijakan pemerintah Prancis pada masa itu.'),
(17, 'The Garden of Earthly Delights', 'Hieronymus Bosch', 1510, 'D:\\Dokumen\\Semester 5\\PBO\\Project\\src\\Karya\\The Garden of Earthly Delights.jpeg', 'Lukisan', '\"The Garden of Earthly Delights\" adalah sebuah karya masterpiece yang dihasilkan oleh pelukis Belanda Hieronymus Bosch pada akhir abad ke-15 atau awal abad ke-16. Lukisan ini selesai dibuat sekitar tahun 1490 hingga 1510 dan menjadi salah satu karya terpenting dan paling kontroversial dalam sejarah seni rupa Barat. Bosch dikenal akan gaya fantastis dan surrealnya, dan \"The Garden of Earthly Delights\" merupakan manifestasi penuh warna dari imajinasinya yang luar biasa.\n\nLukisan ini terdiri dari tiga panel besar yang dapat dilipat. Panel pertama menggambarkan Taman Eden, panel kedua menampilkan pemandangan dunia yang penuh dengan kenikmatan duniawi dan kehidupan sehari-hari, sedangkan panel ketiga menggambarkan siksaan dan kehancuran dalam depiksi neraka. Setiap panel penuh dengan detail-detail kecil yang menggambarkan berbagai adegan dan makhluk, menciptakan tampilan yang rumit dan kompleks. Lukisan ini telah menjadi subjek interpretasi dan kontroversi selama berabad-abad karena keunikan dan unsur misteriusnya, membuatnya menjadi salah satu karya seni yang paling diperdebatkan.\n\nDeskripsi visual \"The Garden of Earthly Delights\" mencerminkan kekayaan imajinasi Bosch yang tak terbatas. Lukisan ini mengeksplorasi tema-tema kehidupan, dosa, dan keabadian dengan cara yang surreal dan alegoris. Gaya dan pemilihan warna Bosch menciptakan suasana yang mengesankan dan tidak seperti lukisan lain pada zamannya. \"The Garden of Earthly Delights\" tetap menjadi karya seni yang menarik perhatian, memicu pertanyaan dan interpretasi yang beragam, dan menghadirkan tantangan artistik yang masih relevan hingga saat ini.');

-- --------------------------------------------------------

--
-- Table structure for table `quiz`
--

CREATE TABLE `quiz` (
  `no` int(50) NOT NULL,
  `question` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `quiz`
--

INSERT INTO `quiz` (`no`, `question`) VALUES
(1, 'Apa nama dari karya di atas?'),
(2, 'Tahun berapa karya di atas diciptakan?'),
(3, 'Siapa yang menciptakan karya di atas?');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
