/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class art extends javax.swing.JPanel {
    public static int size = 0;
    public String name, artist;
    public String desk;
    public int tahun = 0;
    public ImageIcon img;
    /**
     * Creates new form art
     */
    public art() {
        initComponents();
        image.setSize(169, 195); 
    }
    
    public static int ukuran(){
        return size;
    }
    
    public void setImage(String nama){
        Connection con = Connect.getConnection();
        try{
            String query = "SELECT nama, tahun, artist, gambar, deskripsi FROM art WHERE nama = ?";
            try(PreparedStatement stmt = con.prepareStatement(query)){
                stmt.setString(1, nama);
                try(ResultSet rs = stmt.executeQuery()){
                    while(rs.next()){
                        name = rs.getString("nama");
                        tahun = rs.getInt("tahun");
                        artist = rs.getString("artist");
                        desk = rs.getString("deskripsi");
                        Blob blob = rs.getBlob("gambar");
                        byte[] imageData = blob.getBytes(1, (int) blob.length());
                        ImageIcon imageIcon = new ImageIcon(imageData);
                        img = imageIcon;
                        Image originalImage = imageIcon.getImage();
                        Image scaledImage = originalImage.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon scaled = new ImageIcon(scaledImage);
                        image.setIcon(scaled);
                        title.setText(name);
                    }
                }
            }catch(Exception e){
            
        }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(205, 268));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Description desc = new Description();
        desc.setDesc(name, artist, tahun, img, desk);
        desc.setLocationRelativeTo(null);
        desc.setVisible(true);
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBorder(BorderFactory.createLineBorder(Color.black, 2));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBorder(BorderFactory.createLineBorder(Color.black, 1));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel image;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
